name: PR

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repositori
        uses: actions/checkout@v2

      - name: Set up Node.Js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: echo "hola"

      - name: Lint TypeScript
        run: npm run lint