name: Re-usable Workflow

on:
  pull_request:
    branches:
      - master

jobs:
  Reusable:
    uses: Fundacion-Instituto-Profesional-Duoc-UC/AUY1102-Pipeline/.github/workflows/reusable-workflow.yml@v1.1.0